# Site settings
title: Moshe Weitzman
description: "https://www.tumblr.com/blog/weitzman"
url: "http://weitzman.github.io/blog"
author:
  name: "Moshe Weitzman"
  email: "weitzman@tejasa.com"
  url: "http://weitzman.github.io/blog"

# Build settings
baseurl: /blog # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
